// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odxpmogjybvnnjeessis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9keHBtb2dqeWJ2bm5qZWVzc2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NDMzODUsImV4cCI6MjA3ODQxOTM4NX0.2kdoQJvGRqx9pwFw9dSt3PEH_T4C6_5WUePk21Eldco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);